export const Products = [
  {
    id: "1",
    img: "/assets/lipstick.jpg",
    title: "Lipstick",
    price: "$19.99",
    category: "MakeupEssentials",
  },
  {
    id: "2",
    img: "/assets/pallete.jpg",
    title: "Palette",
    price: "$19.99",
    category: "MakeupEssentials",
  },
  {
    id: "3",
    img: "/assets/gloss.jpg",
    title: "Gloss",
    price: "$19.99",
    category: "MakeupEssentials",
  },
  {
    id: "4",
    img: "/assets/eyeliner.jpg",
    title: "Eye Liner",
    price: "$19.99",
    category: "MakeupEssentials",
  },
  {
    id: "5",
    img: "/assets/Flower-claw1.jpg",
    title: "Flower claws",
    price: "$19.99",
    category: "HairAccessories",
  },
  {
    id: "6",
    img: "/assets/square-claw.jpg",
    title: "Square claws",
    price: "$19.99",
    category: "HairAccessories",
  },
  {
    id: "7",
    img: "/assets/Flower-claw2.jpg",
    title: "Flower claws",
    price: "$19.99",
    category: "HairAccessories",
  },
  {
    id: "8",
    img: "/assets/Scrunchie-1.jpg",
    title: "Scrunchie",
    price: "$19.99",
    category: "HairAccessories",
  },
  {
    id: "9",
    img: "/assets/Scrunchie-2.jpg",
    title: "Scrunchie",
    price: "$19.99",
    category: "HairAccessories",
  },
  {
    id: "10",
    img: "/assets/star-clip.jpg",
    title: "Star clips",
    price: "$19.99",
    category: "HairAccessories",
  },
  {
    id: "11",
    img: "/assets/brushe-4.jpg",
    title: "Makeup Brushes",
    price: "$19.99",
    category: "BlendBluffs",
  },
  {
    id: "12",
    img: "/assets/brush-1.jpg",
    title: "Makeup Brushes",
    price: "$19.99",
    category: "BlendBluffs",
  },
  {
    id: "13",
    img: "/assets/brush-2.jpg",
    title: "Makeup Brushes",
    price: "$19.99",
    category: "BlendBluffs",
  },
  {
    id: "14",
    img: "/assets/brush-3.jpg",
    title: "Makeup Brushes",
    price: "$19.99",
    category: "BlendBluffs",
  },
  {
    id: "15",
    img: "/assets/sponge-2.jpg",
    title: "Blending Sponges",
    price: "$19.99",
    category: "BlendBluffs",
  },
  {
    id: "16",
    img: "/assets/sponge-1.jpg",
    title: "Blending Sponges",
    price: "$19.99",
    category: "BlendBluffs",
  },
  {
    id: "17",
    img: "/assets/rings.jpg",
    title: "Rings",
    price: "$19.99",
    category: "PreetyGems",
  },
  {
    id: "18",
    img: "/assets/Moon braclet.jpg",
    title: "Moon Braclets",
    price: "$19.99",
    category: "PreetyGems",
  },
  {
    id: "19",
    img: "/assets/pendant.jpg",
    title: "Pendant",
    price: "$19.99",
    category: "PreetyGems",
  },
  {
    id: "20",
    img: "/assets/clover bracelet.jpg",
    title: "Clove Braclets",
    price: "$19.99",
    category: "PreetyGems",
  },
];